agilent2dicom.py: comment out no of k-space traj, diff directionality bug dpush: incorrect test order for MASSIVEUSERNAME fdf2dcm.sh: dcmodify is statement improved fdf2dicom: New Check button that calls dcheck.sh.  Bug on Agilent console due to csh/bash incompatibilities fix-dicoms.sh: MASSIVE test updated and header added

diff --git a/dpush b/dpush
--- a/dpush
+++ b/dpush
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # filename: dpush
 # description: push all DICOM files to DaRIS
 # input: cid, directory of DICOM file
@@ -23,18 +23,23 @@
 #     You should have received a copy of the GNU General Public License
 #     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
+# test ${MASSIVEUSERNAME+defined} || echo "MASSIVUSERNAME not found"
 #Check whether we are on MASSIVE or the Agilent console (Redhat 6.5)
 if test ${MASSIVEUSERNAME+defined}; then 
-    DCMTK="/home/vnmr1/src/dcmtk-3.6.0/bin"
-    FDF2DCMPATH="/home/vnmr1/src/Agilent2Dicom"
-# load dcm tools
-# DCMODIFY=./dcmtools/bin/DCMODIFY
-    export PATH=${PATH}:${DCMTK}
-else
     FDF2DCMPATH=$(dirname $0)
     # export PATH=${PATH}:${DCMTK}
+else
+    DCMTKPATH="/home/vnmr1/src/dcmtk-3.6.0/bin"
+    FDF2DCMPATH="/home/vnmr1/src/Agilent2Dicom"
+    echo $DCMTKPATH
+    echo $FDF2DCMPATH
+# load dcm tools
+# DCMODIFY=./dcmtools/bin/DCMODIFY
+    export PATH=${PATH}:${DCMTKPATH}
 fi
+
+test -x storescu || (echo "storescu not found"; exit 1)
+
 STORESCU="storescu --debug --arguments --verbose " 
 #"java -cp `dirname $0`/../lib/dcmtools.jar nig.dicom.util.StoreSCU"
 
